barbadus_agendamento:
    resource: "@BarbadusBundle/Controller/AgendamentoController.php"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

barbadus:
    resource: "@BarbadusBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

